import { Poppins } from 'next/font/google'
import Header from './components/Header'
import { ClerkProvider } from '@clerk/nextjs'
import { light } from '@clerk/themes'
import Footer from './components/Footer'
import './globals.css'

const poppins = Poppins({
  weight: ['400', '700'],
  subsets: ['latin'],
});

export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={{
      baseTheme: light,
    }}>
    <html lang="en">   
      <body className={ poppins.className }>
        <Header />
        <main className='container'>
          {children}
        </main>
        <Footer />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.js"></script>

      </body>
    </html>
    </ClerkProvider>
  )
}
